/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jazzy
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IDNumberLabel = new javax.swing.JLabel();
        IDNumberField = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        CourseLabel = new javax.swing.JLabel();
        CourseField = new javax.swing.JTextField();
        UnitsLabel = new javax.swing.JLabel();
        UnitsField = new javax.swing.JTextField();
        TuitionLabel = new javax.swing.JLabel();
        TuitionField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        presidential = new javax.swing.JCheckBox();
        academic = new javax.swing.JCheckBox();
        working = new javax.swing.JCheckBox();
        athletic = new javax.swing.JCheckBox();
        sugbo = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        Library = new javax.swing.JCheckBox();
        Laboratory = new javax.swing.JCheckBox();
        Clinic = new javax.swing.JCheckBox();
        Lms = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STATEMENT OF ACCOUNT");

        IDNumberLabel.setText("ID Number:");

        IDNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDNumberFieldActionPerformed(evt);
            }
        });

        NameLabel.setText("Name:");

        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        CourseLabel.setText("Course:");

        CourseField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseFieldActionPerformed(evt);
            }
        });

        UnitsLabel.setText("Units Enrolled:");

        UnitsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnitsFieldActionPerformed(evt);
            }
        });

        TuitionLabel.setText("Tuition Fee:");

        TuitionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuitionFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("SCHOLARSHIP");

        presidential.setText("PRESIDENTIAL(90%)");
        presidential.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presidentialActionPerformed(evt);
            }
        });

        academic.setText("ACADEMIC(80%)");
        academic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                academicActionPerformed(evt);
            }
        });

        working.setText("WORKING(90%)");
        working.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workingActionPerformed(evt);
            }
        });

        athletic.setText("ATHLETIC(70%)");
        athletic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                athleticActionPerformed(evt);
            }
        });

        sugbo.setText("SUGBO(20%)");
        sugbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sugboActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("MISCELLANEOUS");

        Library.setText("LIBRARY");
        Library.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryActionPerformed(evt);
            }
        });

        Laboratory.setText("LABORATORY");
        Laboratory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaboratoryActionPerformed(evt);
            }
        });

        Clinic.setText("CLINIC");
        Clinic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClinicActionPerformed(evt);
            }
        });

        Lms.setText("LMS");
        Lms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LmsActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calculate");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UnitsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IDNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TuitionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IDNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CourseField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UnitsField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TuitionField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(academic)
                            .addComponent(working)
                            .addComponent(athletic)
                            .addComponent(sugbo)
                            .addComponent(presidential)
                            .addComponent(Library)
                            .addComponent(Laboratory)
                            .addComponent(Clinic)
                            .addComponent(Lms)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnitsField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UnitsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TuitionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(TuitionField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(presidential)
                .addGap(18, 18, 18)
                .addComponent(academic)
                .addGap(18, 18, 18)
                .addComponent(working)
                .addGap(18, 18, 18)
                .addComponent(athletic)
                .addGap(18, 18, 18)
                .addComponent(sugbo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Library)
                .addGap(18, 18, 18)
                .addComponent(Laboratory)
                .addGap(18, 18, 18)
                .addComponent(Clinic)
                .addGap(18, 18, 18)
                .addComponent(Lms)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDNumberFieldActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void CourseFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseFieldActionPerformed

    private void UnitsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnitsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnitsFieldActionPerformed

    private void TuitionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuitionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuitionFieldActionPerformed

    private void presidentialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presidentialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_presidentialActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String id = IDNumberField.getText().trim();
    String name = NameField.getText().trim();
    String course = CourseField.getText().trim();
    String unitsText = UnitsField.getText().trim();

    if (id.isEmpty() || name.isEmpty() || course.isEmpty() || unitsText.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in ID, Name, Course and Units.", "Missing data", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int units = 0;
    try {
        units = Integer.parseInt(unitsText);
        if (units < 0) throw new NumberFormatException();
    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Units must be a positive integer.", "Invalid input", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Tuition per unit
    double tuitionPerUnit = 1000.0;
    double tuition = units * tuitionPerUnit;

    // Scholarship selection
    String scholarshipName = "None";
    double discountRate = 0.0;
    int scholarshipCount = 0;

    if (presidential.isSelected()) {
        scholarshipName = "Presidential (90%)";
        discountRate = 0.90;
        scholarshipCount++;
    }
    if (academic.isSelected()) {
        scholarshipName = "Academic (80%)";
        discountRate = 0.80;
        scholarshipCount++;
    }
    if (working.isSelected()) {
        scholarshipName = "Working (80%)";
        discountRate = 0.80;
        scholarshipCount++;
    }
    if (athletic.isSelected()) {
        scholarshipName = "Athletic (70%)";
        discountRate = 0.70;
        scholarshipCount++;
    }
    if (sugbo.isSelected()) {
        scholarshipName = "Sugbo (20%)";
        discountRate = 0.20;
        scholarshipCount++;
    }

    if (scholarshipCount > 1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Only ONE scholarship can be selected!", "Scholarship selection", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Calculate balance: tuition minus scholarship
    double scholarshipDeduction = tuition * discountRate;
    double balance = tuition - scholarshipDeduction;

    // Miscellaneous fees as string (for display only)
    String miscStr = "";
    if (Library.isSelected())    miscStr += "Library ";
    if (Laboratory.isSelected()) miscStr += "Laboratory ";
    if (Clinic.isSelected())     miscStr += "Clinic ";
    if (Lms.isSelected())        miscStr += "LMS ";
    miscStr = miscStr.trim(); // remove trailing space

    // Convert values to strings for Result form
    String unitsStr = String.valueOf(units);
    String tuitionStr = String.format("%.2f", tuition);       // Original tuition
    String scholarshipStr = scholarshipName;
    String balanceStr = String.format("%.2f", balance);       // Tuition - scholarship

    // Pass exactly 8 parameters to your Result constructor
    Result resultPage = new Result(
            id,
            name,
            course,
            unitsStr,
            tuitionStr,
            scholarshipStr,
            miscStr,
            balanceStr
    );

    resultPage.setVisible(true);
    this.dispose();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void academicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_academicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_academicActionPerformed

    private void workingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workingActionPerformed

    private void athleticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_athleticActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_athleticActionPerformed

    private void sugboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sugboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sugboActionPerformed

    private void LibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibraryActionPerformed

    private void LaboratoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaboratoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LaboratoryActionPerformed

    private void ClinicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClinicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClinicActionPerformed

    private void LmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LmsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Clinic;
    private javax.swing.JTextField CourseField;
    private javax.swing.JLabel CourseLabel;
    private javax.swing.JTextField IDNumberField;
    private javax.swing.JLabel IDNumberLabel;
    private javax.swing.JCheckBox Laboratory;
    private javax.swing.JCheckBox Library;
    private javax.swing.JCheckBox Lms;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField TuitionField;
    private javax.swing.JLabel TuitionLabel;
    private javax.swing.JTextField UnitsField;
    private javax.swing.JLabel UnitsLabel;
    private javax.swing.JCheckBox academic;
    private javax.swing.JCheckBox athletic;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox presidential;
    private javax.swing.JCheckBox sugbo;
    private javax.swing.JCheckBox working;
    // End of variables declaration//GEN-END:variables
}
